import Image from "next/image";

import biggby from "@/public/images/projects/biggby.png";
import biggbyCheckout from "@/public/images/projects/biggbyCheckout.png";

import { ExternalLink, StackList } from "./ui";

/**
 * Disc Channel — the featured project. All claims come from cv.md:
 * the BIGGBY Coffee experience entry ($12.0M, team of 3, full lifecycle)
 * and the addendum project details (description, live link, screenshots).
 */

/** Pure-CSS Wii disc: silver sheen, center hole, gentle motion-safe spin. */
function SpinningDisc() {
    return (
        <div
            aria-hidden="true"
            className="flex shrink-0 flex-col items-center gap-3"
        >
            <div className="relative h-36 w-36 sm:h-44 sm:w-44">
                <div
                    className="absolute inset-0 rounded-full border border-wii-line bg-[conic-gradient(from_220deg,var(--color-wii-white),var(--color-wii-bg)_22%,var(--color-wii-white)_46%,var(--color-wii-bg-light)_60%,var(--color-wii-bg)_78%,var(--color-wii-white))] shadow-wii motion-safe:animate-spin"
                    style={{ animationDuration: "9s" }}
                >
                    <div className="absolute inset-[13%] rounded-full border border-wii-line/50" />
                    <div className="absolute inset-[24%] rounded-full border border-wii-line/35" />
                </div>
                <div className="absolute top-1/2 left-1/2 h-10 w-10 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-wii-line bg-wii-bg-light shadow-[inset_0_1px_3px_rgba(60,90,120,0.25)]" />
            </div>
            {/* The disc slot itself */}
            <div className="h-2 w-28 rounded-full border border-wii-line bg-wii-white shadow-[inset_0_1px_2px_rgba(34,169,224,0.45)]" />
        </div>
    );
}

export default function DiscSection() {
    return (
        <div className="mx-auto flex w-full max-w-4xl flex-col gap-6">
            {/* Disc + headline */}
            <section className="rounded-channel border border-wii-line bg-linear-to-b from-white to-wii-bg-light p-6 shadow-wii-sm sm:p-8">
                <div className="flex flex-col items-center gap-6 text-center sm:flex-row sm:gap-8 sm:text-left">
                    <SpinningDisc />
                    <div className="flex min-w-0 flex-col items-center gap-3 sm:items-start">
                        <p className="font-display text-[11px] font-medium tracking-[0.2em] text-wii-blue-deep uppercase">
                            Now in the disc slot
                        </p>
                        <h3 className="font-display text-xl font-medium tracking-wide text-wii-text sm:text-2xl">
                            BIGGBY Coffee — Online Ordering Platform
                        </h3>
                        <p className="text-sm leading-relaxed text-wii-text/90 sm:text-base">
                            A seamless app and web ordering experience for
                            BIGGBY Coffee: customers build a drink and send the
                            order to the store of their choosing, with a strong
                            focus on UX across devices. Built during my time at
                            BIGGBY (2020–2021), where I managed the platform
                            through its full development lifecycle.
                        </p>
                        <StackList
                            label="BIGGBY platform tech stack"
                            items={[
                                "React",
                                "Redux",
                                "TypeScript",
                                "GraphQL",
                                "AWS"
                            ]}
                        />
                        <ExternalLink href="https://app.biggby.com">
                            Live — app.biggby.com
                        </ExternalLink>
                    </div>
                </div>
            </section>

            {/* Highlight strip */}
            <section aria-label="BIGGBY platform highlights">
                <dl className="grid gap-3 sm:grid-cols-3 sm:gap-4">
                    <div className="flex flex-col rounded-2xl border border-wii-line bg-wii-white p-4 text-center shadow-wii-sm">
                        <dt className="order-2 mt-1 text-xs text-wii-text/70">
                            in revenue generated by the platform
                        </dt>
                        <dd className="font-display text-2xl font-medium text-wii-blue-deep">
                            $12.0M
                        </dd>
                    </div>
                    <div className="flex flex-col rounded-2xl border border-wii-line bg-wii-white p-4 text-center shadow-wii-sm">
                        <dt className="order-2 mt-1 text-xs text-wii-text/70">
                            junior engineers led and mentored
                        </dt>
                        <dd className="font-display text-2xl font-medium text-wii-blue-deep">
                            Team of 3
                        </dd>
                    </div>
                    <div className="flex flex-col rounded-2xl border border-wii-line bg-wii-white p-4 text-center shadow-wii-sm">
                        <dt className="order-2 mt-1 text-xs text-wii-text/70">
                            built, deployed, and maintained
                        </dt>
                        <dd className="font-display text-2xl font-medium text-wii-blue-deep">
                            Full lifecycle
                        </dd>
                    </div>
                </dl>
            </section>

            {/* Screenshots */}
            <section aria-label="BIGGBY platform screenshots">
                <div className="grid gap-4 sm:grid-cols-2">
                    <figure className="overflow-hidden rounded-channel border border-wii-line bg-wii-white shadow-wii-sm">
                        <div className="relative aspect-[16/10] w-full overflow-hidden border-b border-wii-line bg-wii-bg-light">
                            <Image
                                src={biggby}
                                alt="BIGGBY online ordering drink builder — customizing a Caramel Marvel latte with size, shot count, and flavor options"
                                fill
                                sizes="(min-width: 640px) 28rem, 100vw"
                                className="object-cover"
                            />
                        </div>
                        <figcaption className="px-4 py-3 text-xs text-wii-text/70">
                            Build Yours — drink customization in the ordering
                            flow
                        </figcaption>
                    </figure>
                    <figure className="overflow-hidden rounded-channel border border-wii-line bg-wii-white shadow-wii-sm">
                        <div className="relative aspect-[16/10] w-full overflow-hidden border-b border-wii-line bg-wii-bg-light">
                            <Image
                                src={biggbyCheckout}
                                alt="BIGGBY online ordering checkout screen with pickup details and an order summary"
                                fill
                                sizes="(min-width: 640px) 28rem, 100vw"
                                className="object-cover"
                            />
                        </div>
                        <figcaption className="px-4 py-3 text-xs text-wii-text/70">
                            Checkout — pickup details and order summary
                        </figcaption>
                    </figure>
                </div>
            </section>
        </div>
    );
}
